---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghidra-samples-pvc
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: {{ .Values.sampleStorage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.sampleStorage.size }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-ghidra
spec:
  serviceName: "{{ .Release.Name }}-ghidra"
  replicas: 1
  selector:
    matchLabels:
      app: ghidra
  template:
    metadata:
      labels:
        app: ghidra
    spec:
      containers:
      - name: ghidra
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - "server"
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
        - name: MAXMEM
          value: "4G"
        volumeMounts:
        - name: samples
          mountPath: /samples
      volumes:
      - name: samples
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-samples-pvc
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ghidra-main
spec:
  routes:
  - match: HostSNI(`*`)
    services:
    - name: {{ .Release.Name }}-ghidra-service
      port: 13100
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ghidra-service
spec:
  type: ClusterIP
  ports:
  - name: ghidra-main
    port: 13100
    targetPort: 13100
  - name: ghidra-1
    port: 13101
    targetPort: 13101
  - name: ghidra-2
    port: 13102
    targetPort: 13102
  selector:
    app: ghidra