---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghidra-samples-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.sampleStorage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.sampleStorage.size }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ghidra
spec:
  serviceName: "ghidra"
  replicas: 1
  selector:
    matchLabels:
      app: ghidra
  template:
    metadata:
      labels:
        app: ghidra
    spec:
      containers:
        - name: ghidra
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "server"
          resources: {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: MAXMEM
              value: {{ .Values.memoryRequest }}
          volumeMounts:
            - name: samples
              mountPath: {{ .Values.sampleStorage.mountPath }}
      volumes:
        - name: samples
          persistentVolumeClaim:
            claimName: ghidra-samples-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ghidra-service
spec:
  type: LoadBalancer
  ports:
    {{- toYaml .Values.service.ports | nindent 4 }}
  selector:
    app: ghidra